# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend Node.js CI

on:
  push:
    branches: [ "master" ]
    paths:
       -Frontend/**
  pull_request:
    branches: [ "master" ]
    paths:
       -Frontend/**

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: "☁️ checkout repository"
      uses: actions/checkout@v4
      
    - name: "🔧 setup node"
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: "🔧 install npm@latest"
      run: npm ci
      working-directory: ./Frontend
      
    - name: "🔧 build"  
      run: npm run build --if-present
      working-directory: ./Frontend
      
    - name: "🔍 run tests"
      run: npm test --if-present
      working-directory: ./Frontend

  lint:
    name: Code standards
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v4

      - name: "🔧 setup node"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: "🔧 install npm@latest"
        run: npm ci
        working-directory: ./Frontend
        
      - name: "🔧 build"  
        run: npm run build --if-present
        working-directory: ./Frontend

      - name: "🔍 lint code"
        run: npm run lint --if-present
        working-directory: ./Frontend
